matrix:
  include:
      - os: linux
        sudo: required
        llvm: 3.8

language: cpp

compiler:
- clang

install:
- sudo apt-get install clang
- wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
- tar -xvzf bison-3.0.4.tar.gz
- cd bison-3.0.4
- ./configure && make && sudo make install
- cd ..
- sudo apt-get install flex

script:
- make
