matrix:
  include:
    - compiler: clang
      addons:
          apt:
            sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main'
              key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
            packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

language: cpp

install:
- sudo apt-get install clang
- wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
- tar -xvzf bison-3.0.4.tar.gz
- cd bison-3.0.4
- ./configure && make && sudo make install
- cd ..
- sudo apt-get install flex

script:
- make